### ISSUE TITLE
7. Update "data logging" materials

### ISSUE THREAD

**Issue by agstephens** [tommygod3/ncas-isc#8]
Presentations and related materials:

https://github.com/tommygod3/ncas-isc/tree/master/python/presentations/logging-data-from-serial-ports

This content was created by Dan Walker (NCAS Leeds) who teaches on the course and we will need to liaise with him about updating and testing this (because we don't have a serial logger instrument to test).

Data/code files:

 - check anything referenced in: presentations, exercises and solutions
 - Code: https://github.com/tommygod3/ncas-isc/tree/master/python/exercises/example_code
 - Data: https://github.com/tommygod3/ncas-isc/tree/master/python/exercises/example_data

**Comment by tommygod3** [comment]
Updated, tested and reuploaded pdfs
